parameters:
- name: stages
  type: stageList
  default: []

- name: pool
  type: object
  default: {}

- name: containers
  type: object
  default: {}

stages:
  - ${{ each stage in parameters.stages }}:
    - stage: ${{ stage.stage }}
      jobs:
        - ${{ each job in stage.jobs }}:
          - job: ${{ job.job }}
            displayName: ${{ job.displayName }}
            container: ${{ parameters.containers[ job.containerKey ] }}
            steps:
              - ${{ each step in job.steps }}
                displayName: ${{ step.displayName }}
                - ${{ step }}