parameters:
- name: stage
  type: stage
  default: {}

- name: pool
  type: object
  default: {}

- name: containers
  type: object
  default: {}

jobs:
- job: Setup
  pool: ${{ parameters.stage.pool }}
    vmImage: ${{ parameters.stage.pool.image }}

  ${{ if parameters.containers.default_linux_container.image }}:
    container:
      ${{ each pair in parameters.containers.default_linux_container }}:
        ${{ if ne(pair.key, 'name') }}:
          ${{ pair.key }}: ${{ pair.value }}
      name: default_linux_container