parameters:
- name: stage
  type: stage
  default: {}

- name: pool
  type: object
  default: {}

- name: containers
  type: object
  default: {}

stages:
  - ${{ parameters.stage }}:
    jobs:
      - job: ${{ parameters.stage.jobs.job }}
    pool: 
      vmImage: ${{ parameters.pool.vmImage }}

    container:
      ${{ each pair in parameters.containers.default_linux_container }}:
        ${{ if ne(pair.key, 'name') }}:
          ${{ pair.key }}: ${{ pair.value }}
      name: default_linux_container