parameters:
  - name: jobs
    type: object

  - name: vmImage
    type: string
    default: 'ubuntu-latest'

  - name: container
    type: string

stages:
  - stage: BuildStage
    jobs:
      ${{ each job in parameters.jobs }}
      - job:
        pool:
          vmImage: ${{ parameters.vmImage }}
        container:
          image: ${{ parameters.container }}
        steps: ${{ job.steps }}
        ${{ if containsValue(job, 'dependsOn')}}
          dependsOn: ${{ job.dependsOn }}