parameters:
- name: stages
  type: stageList
  default: []

- name: pool
  type: object
  default: {}

- name: containers
  type: object
  default: {}

resources:
  containers:
  - ${{ each container in parameters.containers }}:
    - container: ${{ container.alias }}
      image: ${{ container.image }}

stages:
  - ${{ each stage in parameters.stages }}:
    - stage: ${{ stage.stage }}
      jobs:
        - ${{ each job in stage.jobs }}:
          - job: ${{ job.job }}
            container: ${{ job.container }}
            displayName: ${{ job.displayName }}
            steps:
              - ${{ each step in job.steps }}:
                - ${{ step }}