parameters:
- name: stages
  type: stageList
  default: []

- name: pool
  type: object
  default: {}

- name: containers
  type: object
  default: {}

stages:
  - stage: ${{ parameters.stages.stage }}
    pool: 
      vmImage: ${{ parameters.pool.image }}

    jobs:
    - job: Setup

      ${{ if parameters.containers.default_linux_container.image }}:
        container:
          ${{ each pair in parameters.containers.default_linux_container }}:
            ${{ if ne(pair.key, 'name') }}:
              ${{ pair.key }}: ${{ pair.value }}
          name: default_linux_container