parameters:
- name: stages
  type: stageList
  default: []

- name: containers
  type: object
  default:
    - name: default_linux_container
      image: ubuntu:20.04

resources:
  containers:
  - ${{ each container_pair in parameters.containers }}:
      ${{ if parameters.containers.default_linux_container.image }}:
        container:
          ${{ each pair in parameters.containers.default_linux_container }}:
            ${{ if ne(pair.key, 'name') }}:
              ${{ pair.key }}: ${{ pair.value }}
          name: default_linux_container

stages:
- ${{ each stage in parameters.stages }}:
  - stage: ${{ stage.stage }}
    jobs:
    - ${{ each job in stage.jobs }}:
      - job: ${{ job.job }}
        container:
          ${{ each pair in parameters.containers[job.container.alias] }}:
            ${{ if ne(pair.key, 'name') }}:
              ${{ pair.key }}: ${{ pair.value }}
        steps:
          - ${{ each step in job.steps }}:
            - script: echo "${{ step.key }} = ${{ step.value }}"