parameters:
- name: stages
  type: stageList
  default: []

- name: pool
  type: object
  default: {}

- name: containers
  type: object
  default: {}

resources:
  containers:
  - ${{ each container_pair in parameters.containers }}:
    - ${{ if container_pair.value.image }}:
      - container: ${{ container_pair.key }}
        ${{ each pair in container_pair.value }}:
          ${{ pair.key }}: ${{ pair.value }}

stages:
  - ${{ each stage in parameters.stages }}:
    - stage: ${{ stage.stage }}
      jobs:
        - ${{ each job in stage.jobs }}:
          - job: ${{ job.job }}
            container: ${{ job.container.image }}
            displayName: ${{ job.displayName }}
            steps:
              - ${{ each step in job.steps }}:
                - ${{ step }}