parameters:
- name: stages
  type: stageList
  default: []

- name: containers
  type: object
  default:
    name: default_linux_container
    image: ubuntu:20.04

resources:
  containers: ${{ parameters.containers }}

stages:
- ${{ each stage in parameters.stages }}:
    jobs:
    - ${{ each job in stage.jobs }}:
        container:
          ${{ each pair in parameters.containers[job.container.alias] }}:
            ${{ if ne(pair.key, 'name') }}:
              ${{ pair.key }}: ${{ pair.value }}
        steps:
          - ${{ each step in job.steps }}:
            - script: echo "${{ step.key }} = ${{ step.value }}"