parameters:
- name: stages
  type: stageList
  default: []

- name: pool
  type: object
  default: {}

- name: containers
  type: object
  default: {}

stages:
- ${{ each stage in parameters.stages }}:
  pool: 
    vmImage: ${{ parameters.pool.vmImage }}

  container:
    ${{ each pair in parameters.containers.default_linux_container }}:
      ${{ if ne(pair.key, 'name') }}:
        ${{ pair.key }}: ${{ pair.value }}
    name: default_linux_container