jobs:
- job: BuildJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - script: |
      set -x
      echo "printenv"
      printenv | sort

      alias=$(Resources.TriggeringAlias)
      alias_key=$(echo "${alias}" | sed s/\./_/g | tr '[:lower:]' '[:upper:]')
      runID=RESOURCES_PIPELINE_${alias_key}_RUNID
      echo "Actual-runIDstr: $runID"
      echo "Actual-runID: ${!runID}"

    displayName: Find associated build
    name: Get_Build_Id
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)