# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  pipelines:
  - pipeline: EEEEEEEEEEEE
    source: EEEEEEEEEEEE
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - test

  - pipeline: Example
    source: Example
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - test

pr: none
trigger: none

stages:
- stage: stage
  jobs:
  - job: job
    pool:
      vmImage: 'ubuntu-latest'
    displayName: 'Get pipeline resources'
    steps:
    - script: |
        echo "Expect - runID: $(resources.pipeline.Example.runID)"

        runID=$(Resources.TriggeringAlias)_runID
        sourceCommit=$(Resources.TriggeringAlias)_sourceCommit

        echo "Actual - runID: ${!runID}"
        echo "Actual - sourceCommit: ${!sourceCommit}"

        echo "##vso[task.setvariable variable=runID]$runID"
        echo "##vso[task.setvariable variable=sourceCommit]$sourceCommit"
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: Find associated build
      name: Get_Build_Id
      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
        Example_runID: $(resources.pipeline.Example.runID)
        Example_sourceCommit: $(resources.pipeline.Example.sourceCommit)
        EEEEEEEEEEEE_runID: $(resources.pipeline.EEEEEEEEEEEE.runID)
        EEEEEEEEEEEE_sourceCommit: $(resources.pipeline.EEEEEEEEEEEE.sourceCommit)
    - template: /new-pipeline.yml@self
      parameters:
        runID: $runID
        sourceCommit: $sourceCommit