# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  pipelines:
  - pipeline: dotnet-source-build-pre10.0
    source: dotnet-source-build-pre10.0
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - test

  - pipeline: dotnet-unified-build
    source: dotnet-unified-build
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - test

pr: none
trigger: none

stages:
- stage: stage1
  jobs:
  - template: /new-pipeline.yml@self
