jobs:
- job: BuildJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - script: |
      set -x
      echo "Expect111111111 - alias: $(Resources.TriggeringAlias)"
      echo "printenv"
      printenv | sort

      dotnet_dotnet_build='${{ replace(parameters.dotnetDotnetRunId, ' ', '') }}'
      dotnet_dotnet_sha=''
      alias=$(Resources.TriggeringAlias)//./_
      echo "Actual-alias: $alias"

      pipelineAlias=$(echo $(Resources.PipelineAlias) | sed s/\./_/g | tr '[:upper:]' '[:lower:]')
      runID=RESOURCES_PIPELINE_$pipelineAlias_RUNID
      echo "Actual-runID: ${!runID}"

      # if [[ -z "$dotnet_dotnet_build" ]]; then
      #   if [[ -z "$alias" ]]; then
      #     dotnet_dotnet_build=$(az pipelines runs list --branch '$(Build.SourceBranch)' --organization 'https://dev.azure.com/v-wexu0720' --project 'Test' --pipeline-ids '1' --status completed --top 1 --query "[].id" --output tsv)
      #   else
      #     runID=${alias//[-.]/_}_runID
      #     dotnet_dotnet_build=${!runID}
      #   fi
      # fi
      # id=$(az pipelines runs list --branch '$(Build.SourceBranch)' --organization 'https://dev.azure.com/v-wexu0720' --project 'Test' --pipeline-ids '1' --status completed --top 1 --query "[].id" --output tsv)
      # echo "Latest id: $id"
        
      # if [[ -z "$dotnet_dotnet_build" ]]; then
      #   echo "Could not find a completed dotnet-dotnet build for branch '$(Build.SourceBranch)'"
      #   exit 1
      # fi

      # if [[ -z "$dotnet_dotnet_sha" ]]; then
      #   if [[ -z "$alias" ]]; then
      #     dotnet_dotnet_sha=$(az pipelines build show --organization 'https://dev.azure.com/v-wexu0720' --project 'Test' --id "$dotnet_dotnet_build" --query "sourceVersion" --output tsv)
      #   else
      #     sourceCommit=${alias//[-.]/_}_sourceCommit
      #     dotnet_dotnet_sha=${!sourceCommit}
      #   fi
      # fi

      # if [[ -z "$dotnet_dotnet_sha" ]]; then
      #   echo "Could not find a completed dotnet-dotnet build for branch '$(Build.SourceBranch)'"
      #   exit 1
      # fi
      
      # echo "Dotnet-dotnet build: https://dev.azure.com/v-wexu0720/Test/_build/results?buildId=$dotnet_dotnet_build&view=results"

      # echo "##vso[build.addbuildtag]dotnet $dotnet_dotnet_sha"
      # echo "##vso[task.setvariable variable=DotnetDotnetBuildId]$dotnet_dotnet_build"

      # echo $dotnet_dotnet_sha AND $dotnet_dotnet_build
    displayName: Find associated build
    name: Get_Build_Id
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)