parameters:
- name: runID
  type: string

- name: sourceCommit
  type: string

jobs:
- job: BuildJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - script: |
      echo "Expect111111111 - runID: $(resources.pipeline.Example.runID)"
      echo "Actual - runID: ${{ parameters.runID }}"
      echo "Actual - sourceCommit: ${{ parameters.sourceCommit }}"

      echo "##vso[build.addbuildtag]dotnet ${{ parameters.sourceCommit }}"
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: Find associated build
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)