jobs:
- job: BuildJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - script: |
      echo "Expect111111111 - alias: $(Resources.TriggeringAlias)"
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: Find associated build
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)