# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  pipelines:
  - pipeline: Example
    source: Example
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - test

pr: none
trigger: none

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - script: |
    #     sleep 120
    #     echo "Done waiting."
    #   displayName: Wait for 2 minutes

    - script: |
        echo $(resources.pipeline.Example.projectID)
        echo $(resources.pipeline.Example.pipelineID)
        echo $(resources.pipeline.Example.runID)
        echo $(resources.pipeline.Example.runURI)
        echo $(resources.pipeline.Example.sourceBranch)
        echo $(resources.pipeline.Example.sourceCommit)
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: Find associated build