jobs:
- job: BuildJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - script: |
      echo "Expect - runID: $(resources.pipeline.Example.runID)"

      runID=$(Resources.TriggeringAlias)_runID
      sourceCommit=$(Resources.TriggeringAlias)_sourceCommit

      echo "Actual - runID: ${!runID}"
      echo "Actual - sourceCommit: ${!sourceCommit}"
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: Find associated build
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
      Example_runID: $(resources.pipeline.Example.runID)
      Example_sourceCommit: $(resources.pipeline.Example.sourceCommit)
      EEEEEEEEEEEE_runID: $(resources.pipeline.EEEEEEEEEEEE.runID)
      EEEEEEEEEEEE_sourceCommit: $(resources.pipeline.EEEEEEEEEEEE.sourceCommit)
