jobs:
- job: BuildJob
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - script: |
      set -x
      printenv | sort

      alias=RESOURCES_PIPELINE_$(Resources.TriggeringAlias)_RUNID
      alias1 = $(echo "${alias}" | tr '[:lower:]' '[:upper:]')
      alias2=${alias2//./_}

    displayName: Find associated build
    name: Get_Build_Id
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)