# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  pipelines:
  - pipeline: Example
    source: Example
    # For releases branches only run on internal/release branches because that's where dependencies flow.
    # Previews don't have internal/release branches so they must be run from non-internal release branches.
    trigger:
      branches:
        include:
        - test

pr: none
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: dotnetDotnetRunId
  displayName: 'Specific dotnet-dotnet run ID number (e.g `2108850`)'
  type: string
  default: ' '

- name: buildName
  type: string
  default: 'Offline_MsftSdk'

- name: targetRid
  type: string
  default: 'centos.9-x64'

- name: architecture
  type: string
  default: 'x64'

- name: publishTestResultsPr
  type: boolean
  default: false


steps:
# - script: |
#     sleep 120
#     echo "Done waiting."
#   displayName: Wait for 2 minutes

- script: |
    echo $(Build.SourceBranchName)
    echo $(Build.SourceVersion)
    echo $(resources.pipeline.Example.sourceBranch)
    echo $(resources.pipeline.Example.sourceCommit)
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: Find associated build
  name: Get_Build_Id