parameters:

- name: job
  type: job
  default: {}

- name: stage
  type: stage
  default: {}

- name: sdl
  type: object
  default: {}

- name: pool
  type: object

- name: container
  type: object
  default: {}

- name: authenticatedContainerRegistries
  type: object
  default: null

- name: settings
  type: object

- name: internalConfig
  type: object

- name: isOfficial
  type: boolean

- name: pipelineSdl
  type: object

- name: spokeEsEnforcedSdl
  type: object

- name: featureFlags
  type: object

- name: serviceTreeId
  type: string

- name: supportedBuildWorkflowsInCore
  type: object
  default:
  - Rust

- name: supportedBuildWorkflowsInOneES
  type: object
  default:
  - BuildXL
  - CustomBuild
  - DotNet
  - MSBuild
  - SecureAdoExtension

- name: supportedReleaseWorkflows
  type: object
  default:
  - ev2-classic
  - ev2-ra
  - m365-boc
  - m365-custom
  - m365-ev2-classic
  - m365-ev2-ra
  - m365-replication
  - m365-stratus-app
  - Rust
  - SecureAdoExtension
  - stratus-app
  - stratus-data

- name: predefinedOneESPTVariables
  type: object

- name: skipAutoInjectedTasksVariables
  type: object

- name: ev2ManagedSdpRolloutConfig
  type: object
  default: {}

jobs:
- ${{ if and(parameters.settings.skipSdlSourceScan, ne(parameters.job.pool.name, 'server'), ne(parameters.job.templateContext.type, 'cloudBuildJob'), ne(parameters.job.templateContext.type, 'tagJob')) }}:
  - 'Cannot use "${{ coalesce(parameters.job.templateContext.type, ''agentJob'') }}" when "skipSdlSourceScan" is True. Only serverJob with "asg-cloudtest.asg-cloudtest-servertasks.1ED2E272-8122-4964-9A8B-E1112FC306AA.CloudTestServerBuildTask@2" (and @1) and cloudBuildJob are allowed': error

- ${{ if parameters.job.templateContext.workflow }}:
  - ${{ if or(not(parameters.job.templateContext.type), eq(parameters.job.templateContext.type, 'buildJob')) }}:
    - ${{ if and(not(containsValue(parameters.supportedBuildWorkflowsInCore, parameters.job.templateContext.workflow)), not(containsValue(parameters.supportedBuildWorkflowsInOneES, parameters.job.templateContext.workflow))) }}:
      - 'Unknown build workflow: "${{ parameters.job.templateContext.workflow }}"': error
  - ${{ elseif eq(parameters.job.templateContext.type, 'releaseJob') }}:
    - ${{ if not(containsValue(parameters.supportedReleaseWorkflows, parameters.job.templateContext.workflow)) }}:
      - 'Unknown release workflow: "${{ parameters.job.templateContext.workflow }}"': error
  - ${{ else }}:
    - 'Workflows are supported only for job.templateContext.type "buildJob" or "releaseJob"': error
