parameters:

- name: customBuildTags
  type: object

- name: customLogIssues
  type: object

- name: sdl
  type: object

- name: settings
  type: object

- name: predefinedOneESPTVariables
  type: object

- name: skipAutoInjectedTasksVariables
  type: object

- name: hasCloudBuildJob
  type: boolean

- name: internalConfig
  type: object

- name: stages
  type: stageList

jobs:
- job: Tag
  displayName: 🔒 Tag
  variables:
  - ${{ parameters.skipAutoInjectedTasksVariables }}
  - ${{ parameters.predefinedOneESPTVariables }}
  steps:
  - checkout: none
  - template: ../Steps/Tag.yml
    parameters:
      customBuildTags: ${{ parameters.customBuildTags }}
      customLogIssues: ${{ parameters.customLogIssues }}
      settings: ${{ parameters.settings }}

  - ${{ if eq(parameters.settings.enableRetention, true) }}:
    - template: ../Core/Steps/RunTask.yml
      parameters:
        displayName: Retain the pipeline run
        path: build_retention.py
        continueOnError: true
        env:
          systemAccessToken: $(System.AccessToken)
          systemDefinitionId: $(System.DefinitionId)
          systemCollectionUri: $(System.CollectionUri)
          systemProjectId: $(System.TeamProjectId)
          systemBuildId: $(Build.BuildId)

  - ${{ if eq(parameters.sdl.liquidSecureCheck.enabled, true) }}:
    - template: ../Core/Steps/RunTask.yml
      parameters:
        continueOnError: ${{ eq(parameters.sdl.liquidSecureCheck.failWhenNotCompliant, false) }}
        displayName: '💧 Liquid: SecureCheck'
        path: securecheck_main.py
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          OneES_SUBJECTIDS: ${{ parameters.sdl.liquidSecureCheck.subjectIds }}
          OneES_PROFILES: ${{ parameters.sdl.liquidSecureCheck.profiles }}
          OneES_FAILWHENNOTCOMPLIANT: ${{ parameters.sdl.liquidSecureCheck.failWhenNotCompliant }}

  # Disallow release steps in non release jobs (agentless release cases)
  - ${{ each stage in parameters.stages }}:
    - ${{ each job in stage.jobs }}:
      - ${{ if and(not(eq(job.templateContext.type, 'releaseJob')), eq(job.pool.name, 'server')) }}:
        - template: ../Steps/DisallowReleaseSteps.yml
          parameters:
            job: ${{ job }}
            internalConfig: ${{ parameters.internalConfig }}

  - ${{ if and(parameters.sdl.sourceAnalysisPostSteps, parameters.hasCloudBuildJob) }}:
    - template: ../Steps/SDLPostSteps.yml
      parameters:
        steps: ${{ parameters.sdl.sourceAnalysisPostSteps }}
        continueOnError: true
