parameters:

- name: job
  type: job

- name: internalConfig
  type: object

- name: sdl
  type: object

- name: pool
  type: object

- name: featureFlags
  type: object

- name: settings
  type: object

- name: isOfficial
  type: boolean

- name: scanDirectory
  type: string

- name: artifactName
  type: string

- name: postValidationJobArtifactName
  type: string

- name: sourceRepositoryToCheckout
  type: string

- name: condition
  type: string

- name: deploymentJobUsedInNonReleaseWorkflow
  type: boolean

jobs:
- job: ${{ parameters.job.job }}_${{ coalesce(parameters.postValidationJobArtifactName, replace(parameters.artifactName, '-', '_')) }}_PostValidationJob
  condition: ${{ coalesce(parameters.condition, 'succeeded()') }}
  displayName: ${{ parameters.job.displayName }}_${{ coalesce(parameters.postValidationJobArtifactName, replace(parameters.artifactName, '-', '_')) }}_PostValidationJob
  dependsOn: ${{ parameters.job.job }}
  ${{ if parameters.job.strategy }}:
    strategy: ${{ parameters.job.strategy }}
  variables:
  - template: ../Variables/CommonVariables.yml
    parameters:
      isOfficial: ${{ parameters.isOfficial }}
      os: ${{ parameters.pool.os }}
      authenticatedContainerRegistries: null  # This is not needed for validation jobs
      enforcedTenant: null  # This is not needed for validation jobs
      job: ${{ parameters.job }}
  ${{ if parameters.sdl.postValidationJobAnalysisPool.name }}:
    pool:
      ${{ each pair in parameters.sdl.postValidationJobAnalysisPool }}:
        ${{ if notIn(pair.key, 'image', 'workspace', 'demands') }}:
          ${{ pair.key }}: ${{ pair.value }}
      ${{ if or(parameters.sdl.postValidationJobAnalysisPool.image, parameters.sdl.postValidationJobAnalysisPool.workspace) }}:
        demands:
        - ${{ if parameters.sdl.postValidationJobAnalysisPool.image }}:
          - ImageOverride -equals ${{ parameters.sdl.postValidationJobAnalysisPool.image }}
        - ${{ elseif parameters.sdl.postValidationJobAnalysisPool.workspace }}:
          - ${{ if eq(parameters.sdl.postValidationJobAnalysisPool.os, 'linux') }}:
            - WorkFolder -equals /mnt/${{ parameters.sdl.postValidationJobAnalysisPool.workspace }}
          - ${{ else }}:
            - WorkFolder -equals C:\${{ parameters.sdl.postValidationJobAnalysisPool.workspace }}
        - ${{ elseif and(parameters.sdl.postValidationJobAnalysisPool.demands, not(startsWith(convertToJson(parameters.sdl.postValidationJobAnalysisPool), '['))) }}:
          - ${{ parameters.sdl.postValidationJobAnalysisPool.demands }}
        - ${{ else }}:
          - ${{ each demand in parameters.sdl.postValidationJobAnalysisPool.demands }}:
            - ${{ demand }}
      ${{ elseif parameters.sdl.postValidationJobAnalysisPool.demands }}:
        demands: ${{ parameters.sdl.postValidationJobAnalysisPool.demands }}
  steps:
  - template: ../Steps/PostValidationSteps.yml
    parameters:
      steps: ${{ parameters.job.steps }}
      featureFlags: ${{ parameters.featureFlags }}
      settings: ${{ parameters.settings }}
      scanDirectory: ${{ parameters.scanDirectory }}
      sdl: ${{ parameters.sdl }}
      artifactName: ${{ parameters.artifactName }}
      ${{ if parameters.sdl.postValidationJobAnalysisPool.name }}:
        pool: ${{ parameters.sdl.postValidationJobAnalysisPool }}
      ${{ else }}:
        pool: ${{ parameters.pool }}
      internalConfig: ${{ parameters.internalConfig }}
      sourceRepositoryToCheckout: ${{ parameters.sourceRepositoryToCheckout }}
      isOfficial: ${{ parameters.isOfficial }}
      deploymentJobUsedInNonReleaseWorkflow: ${{ parameters.deploymentJobUsedInNonReleaseWorkflow }}
