parameters:
- name: sdl
  type: object

- name: pool
  type: object

- name: job
  type: job
  default: {}

- name: isOfficial
  type: boolean

- name: pipelineSdl
  type: object

- name: stages
  type: stageList

- name: featureFlags
  type: object

- name: settings
  type: object

- name: predefinedOneESPTVariables
  type: object

- name: skipAutoInjectedTasksVariables
  type: object

- name: internalConfig
  type: object

- name: spokeEsEnforcedSdl
  type: object

- name: customBuildTags
  type: object

- name: customLogIssues
  type: object

jobs:
- ${{ if eq(parameters.sdl.sourceRepositoriesToScan.runInSingleJob, true) }}:
  - template: SDLSourceAnalysisJobInternal.yml
    parameters:
      sdl: ${{ parameters.sdl }}
      pool: ${{ parameters.pool }}
      job: ${{ parameters.job }}
      customBuildTags: ${{ parameters.customBuildTags }}
      customLogIssues: ${{ parameters.customLogIssues }}
      stages: ${{ parameters.stages }}
      featureFlags: ${{ parameters.featureFlags }}
      settings: ${{ parameters.settings }}
      additionalRepositories: ${{ parameters.sdl.sourceRepositoriesToScan.include }}
      predefinedOneESPTVariables: ${{ parameters.predefinedOneESPTVariables }}
      skipAutoInjectedTasksVariables: ${{ parameters.skipAutoInjectedTasksVariables }}
      ${{ if parameters.sdl.customCheckout }}:
        customCheckout: ${{ parameters.sdl.customCheckout }}
      internalConfig: ${{ parameters.internalConfig }}
      isOfficial: ${{ parameters.isOfficial }}
      pipelineSdl: ${{ parameters.pipelineSdl }}
      spokeEsEnforcedSdl: ${{ parameters.spokeEsEnforcedSdl}}

- ${{ else }}:
  - template: SDLSourceAnalysisJobInternal.yml
    parameters:
      sdl: ${{ parameters.sdl }}
      pool: ${{ parameters.pool }}
      job: ${{ parameters.job }}
      customBuildTags: ${{ parameters.customBuildTags }}
      customLogIssues: ${{ parameters.customLogIssues }}
      stages: ${{ parameters.stages }}
      featureFlags: ${{ parameters.featureFlags }}
      settings: ${{ parameters.settings }}
      ${{ if parameters.sdl.customCheckout }}:
        customCheckout: ${{ parameters.sdl.customCheckout }}
      repository:
        repository: self
      predefinedOneESPTVariables: ${{ parameters.predefinedOneESPTVariables }}
      skipAutoInjectedTasksVariables: ${{ parameters.skipAutoInjectedTasksVariables }}
      internalConfig: ${{ parameters.internalConfig }}
      isOfficial: ${{ parameters.isOfficial }}
      pipelineSdl: ${{ parameters.pipelineSdl }}
      spokeEsEnforcedSdl: ${{ parameters.spokeEsEnforcedSdl}}

  - ${{ if parameters.sdl.sourceRepositoriesToScan.include }}:
    - ${{ each repository in parameters.sdl.sourceRepositoriesToScan.include }}:
      - template: SDLSourceAnalysisJobInternal.yml
        parameters:
          sdl: ${{ parameters.sdl }}
          pool: ${{ parameters.pool }}
          job: ${{ parameters.job }}
          stages: ${{ parameters.stages }}
          featureFlags: ${{ parameters.featureFlags }}
          settings: ${{ parameters.settings }}
          ${{ if repository.customCheckout }}:
            customCheckout: ${{ repository.customCheckout }}
          repository: ${{ repository }}
          customBuildTags:  # Intentionally left blank because we already have the customBuildTags in the job for the self repository
          customLogIssues:  # Intentionally left blank because we already have the customLogIssues in the job for the self repository
          predefinedOneESPTVariables: ${{ parameters.predefinedOneESPTVariables }}
          skipAutoInjectedTasksVariables: ${{ parameters.skipAutoInjectedTasksVariables }}
          internalConfig: ${{ parameters.internalConfig }}
          isOfficial: ${{ parameters.isOfficial }}
          pipelineSdl: ${{ parameters.pipelineSdl }}
          spokeEsEnforcedSdl: ${{ parameters.spokeEsEnforcedSdl}}
