parameters:
- name: job
  type: job

- name: settings
  type: object

- name: predefinedOneESPTVariables
  type: object

- name: featureFlags
  type: object

jobs:
# Insert all properties other than those we process separately
- ${{ each pair in parameters.job }}:
    ${{ if notIn(pair.key, 'steps', 'variables') }}:
      # We don't want to include strategy if this is a deployment job, otherwise we want to just include it as it is
      ${{ if not(and(eq(pair.key, 'strategy'), parameters.job.deployment)) }}:
        ${{ pair.key }}: ${{ pair.value }}

  variables:
  - ${{ if parameters.job.variables }}:
    - ${{ each pair2 in parameters.job.variables }}:
      - ${{ if ne(pair2.key, '') }}:
        - name: ${{ pair2.key }}
          value: ${{ pair2.value }}
      - ${{ else }}:
        - ${{ insert }}: ${{ pair2 }}
  - ${{ parameters.predefinedOneESPTVariables }}

  ${{ if parameters.job.deployment }}:
    strategy:
      ${{ each strategyPair in parameters.job.strategy }}:
        ${{ strategyPair.key }}:
          deploy:
            steps:
            - template: ../Steps/UserProvidedAgentlessSteps.yml
              parameters:
                ${{ if strategyPair.value.deploy.steps }}:
                  steps: ${{ strategyPair.value.deploy.steps }}
                workflow: ${{ parameters.job.templateContext.workflow }}
                settings: ${{ parameters.settings }}
                featureFlags: ${{ parameters.featureFlags }}

  ${{ else }}:
    steps:
    - template: ../Steps/UserProvidedAgentlessSteps.yml
      parameters:
        ${{ if parameters.job.steps }}:
          steps: ${{ parameters.job.steps }}
        workflow: ${{ parameters.job.templateContext.workflow }}
        settings: ${{ parameters.settings }}
        featureFlags: ${{ parameters.featureFlags }}
