# This yml is used by these pipelines:
# - dotnet-unified-build (internal)
#   https://dev.azure.com/dnceng/internal/_build?definitionId=1330

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: /eng/pipelines/templates/stages/source-build-and-validate.yml@self
  parameters:
    legs:
      - buildNameFormat: '{0}_Online_MsftSdk'
        distro: centos
        targetArchitecture: x64
        buildFromArchive: false            # 🚫
        enablePoison: false                # 🚫
        runOnline: true                    # ✅
        useMonoRuntime: false              # 🚫
        withPreviousSDK: false             # 🚫