# This yml is used by these pipelines:
# - dotnet-unified-build (internal)
#   https://dev.azure.com/dnceng/internal/_build?definitionId=1330

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: /eng/pipelines/templates/stages/vmr-build.yml@self
  parameters:
    desiredSigning: Unsigned
    desiredIBC: Disabled
    scope: lite