# We don't perform rolling builds and PR triggers are not YAML triggers in AzDO.
trigger: none
pr: none

parameters:
- name: MicrosoftNetCoreAppVersion
  displayName: Runtime package version to use
  type: string
  default: latest

schedules:
- cron: "0 10 * * *"
  displayName: Mon through Sun at 2:00 AM (UTC-8:00)
  branches:
    include:
    - main
  always: true

resources:
  containers:
    - container: linux_arm
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm
      env:
        ROOTFS_DIR: /crossrootfs/arm

    - container: linux_arm64
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm64
      env:
        ROOTFS_DIR: /crossrootfs/arm64

    - container: linux_musl_x64
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64-alpine
      env:
        ROOTFS_DIR: /crossrootfs/x64

    - container: linux_musl_arm
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm-alpine
      env:
        ROOTFS_DIR: /crossrootfs/arm

    - container: linux_musl_arm64
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-arm64-alpine
      env:
        ROOTFS_DIR: /crossrootfs/arm64

    - container: linux_x64
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64
      env:
        ROOTFS_DIR: /crossrootfs/x64

stages:
- stage: build_tests
  displayName: Test asset and harness build
  jobs:
    - template: /eng/pipelines/templates/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/jobs/build.yml
        clrVersion: ${{ parameters.MicrosoftNetCoreAppVersion }}

- stage: run_tests
  displayName: Test Runs (Helix)
  jobs:
    - template: /eng/pipelines/templates/platform-matrix.yml
      parameters:
        jobTemplate: /eng/pipelines/jobs/send-tests-to-helix.yml
        platformList:
        - targetOS: windows
          supportedArchitectures:
          - x86
          - x64
          - arm64
        - targetOS: osx
          supportedArchitectures:
          - x64
          - arm64
        - targetOS: linux
          supportedArchitectures:
          - x64
        # These architectures need further investigation, so they are disabled for now.
          # - arm
          # - arm64
        # - targetOS: linux
        #   osSubgroup: _musl
        #   supportedArchitectures:
        #   - x64
        #   - arm
        #   - arm64
