variables:
- name: EngCommonTemplatesDir
  value: /eng/common/templates-official
- template: ${{ variables.EngCommonTemplatesDir }}/variables/pool-providers.yml@self
- name: Codeql.Enabled
  value: true
- name: TeamName
  value: DotNetSourceBuild
