parameters:
  engCommonTemplatesDir: ''

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Linux
    pool:
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: $(DncEngPublicBuildPool)
        demands: ImageOverride -equals Build.Ubuntu.1804.Amd64.Open
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        name: $(DncEngInternalBuildPool)
        image: 1es-ubuntu-2204
        os: linux
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8
    steps:
    - template: ${{ parameters.engCommonTemplatesDir }}/steps/source-build.yml

    - script: $(Build.SourcesDirectory)/test.sh
      displayName: Run Tests

    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '**/artifacts/TestResults/Release/*.xml'
        testRunTitle: 'Linux_SBRP_tests'
      condition: always()
