stages:
  - template: source-build-and-validate.yml
    parameters:
      isBuiltFromVmr: true
      legs:
        - buildNameFormat: '{0}_Online_MsftSdk'
          distro: centos
          targetArchitecture: x64
          buildFromArchive: false            # 🚫
          enablePoison: false                # 🚫
          runOnline: true                    # ✅
          useMonoRuntime: false              # 🚫
          withPreviousSDK: false             # 🚫